version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ttrss
      MYSQL_DATABASE: ttrss
    volumes:
      - data-db:/var/lib/mysql

  ttrss:
    build: .
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: ttrss
      DB_NAME: ttrss
      SELF_URL_PATH: http://localhost:8080/
    links:
      - db:mysql
    ports:
      - "127.0.0.1:8080:80"

volumes:
  data-db:
    driver: local
